[package]
name = "evalrs"
version = "0.1.0"
authors = ["Serhii Zavadskyi <sz@3yourmind.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.8"
config = { version = "0.10.0", features = ["yaml"] }
env_logger = "0.9.0"
js-sandbox = { git = "https://github.com/Bromeon/js-sandbox", version = "^0.1", branch = "master" }
lru = "0.6.6"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
thiserror = "1.0.26"
log = "0.4.14"

[dependencies.tera]
version = "1.12.1"
default-features = false