FROM rust:1.76 as builder
WORKDIR /app
RUN rustup update
COPY . .
RUN cargo build --release

FROM debian:latest as runtime
RUN apt-get update && apt-get install strace
RUN strace ls -l
WORKDIR /
COPY --from=builder /app/target/release/evalrs /
COPY --from=builder /app/config /config
ENTRYPOINT ["strace", "-f", "./evalrs"]
