name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: login to local repo
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: pull cacher image
        run: docker pull ghcr.io/3yourmind/cacher
        continue-on-error: true
      - name: (re)build cacher image
        run: docker build -t cacher_new --target cacher --cache-from=ghcr.io/3yourmind/cacher .
      - name: tag cacher image
        run: docker tag cacher_new ghcr.io/3yourmind/cacher
      - name: push cacher image
        run: docker push ghcr.io/3yourmind/cacher



      - name: pull builder image
        run: docker pull ghcr.io/3yourmind/builder
        continue-on-error: true

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/evalrs:latest .
      - name: push cacher and builder to the repo
        run: docker push ghcr.io/3yourmind/cacher && docker push ghcr.io/3yourmind/builder

      # - name: login to repo
      #   run: echo ${{secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      # - name: Push docker image
      #   run: docker push ${{secrets.DOCKERHUB_USERNAME}}/evalrs:latest
