name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose

      - name: login to repo
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Build docker image
        run: docker build -t ghcr.io/3yourmind/evalrs:latest .
      - name: Push docker image
        run: docker push ghcr.io/3yourmind/evalrs:latest .
