name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install exact rust compiler
        run: rustup toolchain install 1.76 && rustup default 1.76
      - name: Run tests
        run: cargo test --verbose