name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Build evalrs image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/evalrs:latest -f Dockerfile-ci .

      - name: login to dockerhub repo
        run: echo ${{secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - name: Push evalrs image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/evalrs:latest
