name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: login to repo
        run: echo ${{secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - name: Build docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/evalrs:latest .
      - name: Push docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/evalrs:latest
