name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: login to local repo
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: pull, build and push planner image
        run: | 
          docker pull ghcr.io/3yourmind/planner || true \
          && docker build -t planner_new --target planner --cache-from=ghcr.io/3yourmind/planner . \
          && docker tag planner_new ghcr.io/3yourmind/planner \
          && docker push ghcr.io/3yourmind/planner

      - name: pull, build and push cacher image
        run: | 
          docker pull ghcr.io/3yourmind/cacher || true \
          && docker build -t cacher_new --target cacher --cache-from=ghcr.io/3yourmind/cacher,ghcr.io/3yourmind/planner . \
          && docker tag cacher_new ghcr.io/3yourmind/cacher \
          && docker push ghcr.io/3yourmind/cacher

      - name: pull, build and push builder image
        run: | 
          docker pull ghcr.io/3yourmind/builder || true \
          && docker build -t builder_new --target builder --cache-from=ghcr.io/3yourmind/builder,ghcr.io/3yourmind/cacher,ghcr.io/3yourmind/planner . \
          && docker tag builder_new ghcr.io/3yourmind/builder \
          && docker push ghcr.io/3yourmind/builder

      - name: Build evalrs image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/evalrs:latest --cache-from=ghcr.io/3yourmind/builder .

      - name: login to dockerhub repo
        run: echo ${{secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - name: Push evalrs image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/evalrs:latest
